import { Product } from "./types/Product"

export const sampleProducts: Product[] = [
  {
    name: "Nike",
    slug: "nike-slim-shirt",
    category: "Shirts",
    image: "../images/p1.jpg",
    price: 120,
    countInstock: 10,
    brand: "Nike",
    rating: 5,
    numReviews: 12,
    description: "Good Quality",
  },

  {
    name: "Nike",
    slug: "nike-slim-pant",
    category: "Shirts",
    image: "../images/p2.jpg",
    price: 120,
    countInstock: 10,
    brand: "Nike",
    rating: 5,
    numReviews: 12,
    description: "Good Quality",
  },

  {
    name: "Nike",
    slug: "nike-slim",
    category: "Shirts",
    image: "../images/p3.jpg",
    price: 120,
    countInstock: 10,
    brand: "Nike",
    rating: 5,
    numReviews: 12,
    description: "Good Quality",
  },

  {
    name: "Nike",
    slug: "nike-slim-t",
    category: "Shirts",
    image: "../images/p4.jpg",
    price: 120,
    countInstock: 10,
    brand: "Nike",
    rating: 5,
    numReviews: 12,
    description: "Good Quality",
  },

  {
    name: "Nike",
    slug: "nike-slim-p",
    category: "Shirts",
    image: "../images/p1.jpg",
    price: 120,
    countInstock: 10,
    brand: "Nike",
    rating: 5,
    numReviews: 12,
    description: "Good Quality",
  },
  {
    name: "Nike",
    slug: "nike-slims",
    category: "Shirts",
    image: "../images/p3.jpg",
    price: 120,
    countInstock: 10,
    brand: "Nike",
    rating: 5,
    numReviews: 12,
    description: "Good Quality",
  },
]
